apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-calculator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-calculator-frontend
  template:
    metadata:
      labels:
        app: game-calculator-frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: game-calculator-frontend
          image: localhost:5000/game-calculator-frontend:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: frontend-env
---
apiVersion: v1
kind: Service
metadata:
  name: game-calculator-frontend
spec:
  type: NodePort
  selector:
    app: game-calculator-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000