apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-calculator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-calculator-frontend
  template:
    metadata:
      labels:
        app: game-calculator-frontend
    spec:
      imagePullSecrets:
        - name: game-calc-regcred
      containers:
        - name: game-calculator-frontend
          image: 192.168.6.64:5500/game-calculator-frontend:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: game-calculator-frontend-env
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: game-calculator-frontend
spec:
  type: NodePort
  selector:
    app: game-calculator-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32316