apiVersion: v1
kind: Service
metadata:
  name: game-calculator-frontend
spec:
  selector:
    app: game-calculator-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer